version: '3'

silent: true

includes:
  precommit:
    aliases: [pc]
    taskfile: .taskfiles/PreCommit.yaml

tasks:
  default:
    cmds:
      - task -a

  copy-vendor:
    cmds:
      - rm -r vendor
      - docker cp php-coding-standard_dev:/opt/phpcs/vendor .
      - rm -r vendor-bin/*/vendor
      - docker cp php-coding-standard_dev:/opt/phpcs/vendor-bin/phpcs/vendor vendor-bin/phpcs
      - docker cp php-coding-standard_dev:/opt/phpcs/vendor-bin/phpunit/vendor vendor-bin/phpunit
    preconditions:
      - docker container inspect php-coding-standard_dev >> /dev/null

  context:
    cmds:
      - docker run --rm -it "{{.CONTEXT_IMAGE_HASH}}"
      - docker rmi "{{.CONTEXT_IMAGE_HASH}}"
    vars:
      CONTEXT_IMAGE_HASH:
        sh: docker build -q -f Dockerfile . --target build-context

  dev:
    cmds:
      - docker build -f Dockerfile . -t php-coding-standard:dev --target dev
      - |
        docker run --rm -it \
        -v ./composer.json:/opt/phpcs/composer.json \
        -v ./vendor-bin/phpcs/composer.json:/opt/phpcs/vendor-bin/phpcs/composer.json \
        -v ./vendor-bin/phpcs/composer.lock:/opt/phpcs/vendor-bin/phpcs/composer.lock \
        -v ./vendor-bin/phpunit/composer.json:/opt/phpunit/vendor-bin/phpcs/composer.json \
        -v ./vendor-bin/phpunit/composer.lock:/opt/phpunit/vendor-bin/phpcs/composer.lock \
        -v ./cjw6k:/opt/phpcs/cjw6k \
        -v ./tests:/opt/phpcs/tests \
        -v ./phpcs.xml:/opt/phpcs/phpcs.xml \
        -v ./phpunit.xml:/opt/phpcs/phpunit.xml \
        --name php-coding-standard_dev \
        php-coding-standard:dev

  outdated:
    cmds:
      - docker build -f Dockerfile . -t php-coding-standard:dev --target dev
      - docker run --rm -it --entrypoint composer php-coding-standard:dev outdated
      - docker run --rm -it --entrypoint composer php-coding-standard:dev bin phpcs outdated
      - docker run --rm -it --entrypoint composer php-coding-standard:dev bin phpunit outdated

  test:
    cmds:
      - docker build -f Dockerfile . -t php-coding-standard:test --target test
      - docker run --rm -it php-coding-standard:test
