name: CI

on:
  push:
  schedule:
    - cron: "17 3 * * *"

jobs:
  dev-test:
    runs-on: ubuntu-latest
    name: Run the tests from the Dockerfile
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build -t cjw6k/php-coding-standard -f Dockerfile . --target test

      - name: test
        run: |
          docker run --rm cjw6k/php-coding-standard

  matrix-dev-test:
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: none, ctype, dom, mbstring, simplexml, tokenizer, xmlwriter, xml
          tools: composer

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate composer config
        run: composer validate --no-check-all --strict

      - name: Run composer install
        uses: ramsey/composer-install@v3

      - name: Run tests
        run: composer test
